FROM java:8
WORKDIR /
ADD target/routing-and-filtering-student-1.0-SNAPSHOT.jar routing-and-filtering-student-1.0-SNAPSHOT.jar
EXPOSE 8070
ENTRYPOINT ["java", "-jar", "routing-and-filtering-student-1.0-SNAPSHOT.jar"]