FROM java:8
WORKDIR /
ADD target/routing-and-filtering-book-1.0-SNAPSHOT.jar routing-and-filtering-book-1.0-SNAPSHOT.jar
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "routing-and-filtering-book-1.0-SNAPSHOT.jar"]